### ISSUE TITLE
'Add Category' Feature in Budget Form with Client-Side Validation

### ISSUE THREAD

**Issue by Scolin022** [Dollar-Dynasty/finance-app#20]
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### **TASK:**
Implement a user-friendly 'Add Category' feature within the budget form with a dynamically updating dropdown menu.

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### **PURPOSE:**
When a user adds a category, the system should immediately display the category's title and (if provided) description. 
Categories should be positioned at the top of the category section, which is after the basic budget information in the form.

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### **DETAILS:**
**Category Input Fieldss:**
1. **Category Name**: Required
2. **Description**: Optional field for user
3. **Category Budget Allowance**: Required field
4. **Add Category Button**: Has 50% opacity css styling and disabled. It becomes active and fully opaque once all required category input fields are filled and validated.

**This task will be assigned to two team members:**
- one can focus on the html form creation and dynamic category functionality with JavaScript
- one can focus on client-side validation for the html form with JavaScript, adding basic css for quick error feedback to the user ( example css -> input:valid { } )

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### **SIDE NOTE:**
The 'Add Category' functionality will also be integrated into the budget overview page in the future. This will allow users to add new categories, with the capabilities of editing or deleting them (note: editing and deleting functionalities are not required for this task but for the future).

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by dinaolmelak** [comment]
In the interest of getting more work done for the project, Can I solo this ticket? @Scolin022  That way @bxmtz can get another ticket done.  Will that be ok with you @Scolin022 and @bxmtz?
